2021-05-19 15:39:54,465 INFO    MainThread:7696 [wandb_setup.py:_flush():69] setting env: {}
2021-05-19 15:39:54,466 INFO    MainThread:7696 [wandb_setup.py:_flush():69] setting login settings: {}
2021-05-19 15:39:54,467 INFO    MainThread:7696 [wandb_init.py:_log_setup():336] Logging user logs to C:\Users\Lorenzo\PycharmProjects\flow-forecast\notebooks\wandb\run-20210519_153954-27qrfi1x\logs\debug.log
2021-05-19 15:39:54,467 INFO    MainThread:7696 [wandb_init.py:_log_setup():337] Logging internal logs to C:\Users\Lorenzo\PycharmProjects\flow-forecast\notebooks\wandb\run-20210519_153954-27qrfi1x\logs\debug-internal.log
2021-05-19 15:39:54,469 INFO    MainThread:7696 [wandb_init.py:_jupyter_setup():287] configuring jupyter hooks <wandb.sdk.wandb_init._WandbInit object at 0x000001B046E6C688>
2021-05-19 15:39:54,471 INFO    MainThread:7696 [wandb_init.py:init():369] calling init triggers
2021-05-19 15:39:54,471 INFO    MainThread:7696 [wandb_init.py:init():376] wandb.init called with sweep_config: {}
config: {}
2021-05-19 15:39:54,472 INFO    MainThread:7696 [wandb_init.py:init():418] starting backend
2021-05-19 15:39:54,472 INFO    MainThread:7696 [backend.py:_multiprocessing_setup():71] multiprocessing start_methods=spawn, using: spawn
2021-05-19 15:39:54,480 INFO    MainThread:7696 [backend.py:ensure_launched():123] starting backend process...
2021-05-19 15:39:54,653 INFO    MainThread:7696 [backend.py:ensure_launched():128] started backend process with pid: 10316
2021-05-19 15:39:54,653 INFO    MainThread:7696 [wandb_init.py:init():423] backend started and connected
2021-05-19 15:39:54,653 INFO    MainThread:7696 [wandb_init.py:init():465] updated telemetry
2021-05-19 15:39:54,653 INFO    MainThread:7696 [wandb_init.py:init():484] communicating current version
2021-05-19 15:39:55,621 INFO    MainThread:7696 [wandb_init.py:init():489] got version response upgrade_message: "wandb version 0.10.30 is available!  To upgrade, please run:\n $ pip install wandb --upgrade"

2021-05-19 15:39:55,626 INFO    MainThread:7696 [wandb_init.py:init():497] communicating run to backend with 30 second timeout
2021-05-19 15:39:56,001 INFO    MainThread:7696 [wandb_init.py:init():522] starting run threads in backend
2021-05-19 15:39:56,231 INFO    MainThread:7696 [wandb_run.py:_console_start():1524] atexit reg
2021-05-19 15:39:56,242 INFO    MainThread:7696 [wandb_run.py:_redirect():1371] redirect: SettingsConsole.WRAP
2021-05-19 15:39:56,242 INFO    MainThread:7696 [wandb_run.py:_redirect():1414] Wrapping output streams.
2021-05-19 15:39:56,242 INFO    MainThread:7696 [wandb_run.py:_redirect():1438] Redirects installed.
2021-05-19 15:39:56,242 INFO    MainThread:7696 [wandb_init.py:init():546] run started, returning control to user process
2021-05-19 15:39:56,242 INFO    MainThread:7696 [wandb_init.py:_pause_backend():249] pausing backend
2021-05-19 15:39:56,242 INFO    MainThread:7696 [jupyter.py:save_ipynb():265] not saving jupyter notebook
2021-05-19 15:39:56,249 INFO    MainThread:7696 [wandb_init.py:_resume_backend():258] resuming backend
2021-05-19 15:39:58,698 INFO    MainThread:7696 [wandb_watch.py:watch():39] Watching
2021-05-19 15:43:13,838 INFO    MainThread:7696 [wandb_config.py:__setitem__():141] config set save_path = model_save\19_May_202103_43PM_model.pth - <bound method Run._config_callback of <wandb.sdk.wandb_run.Run object at 0x000001B046E6CD88>>
2021-05-19 15:43:13,838 INFO    MainThread:7696 [wandb_run.py:_config_callback():749] config_cb save_path model_save\19_May_202103_43PM_model.pth None
2021-05-19 15:43:31,162 INFO    MainThread:7696 [wandb_init.py:_pause_backend():249] pausing backend
2021-05-19 15:43:31,163 INFO    MainThread:7696 [jupyter.py:save_ipynb():265] not saving jupyter notebook
